Repository seunghoonKang/we-all-lie-fe, pull requests merged in 2022-12, with the labels that each got.

#68 Feature/gameprogress : 타이머 progress bar 구현
  src/assets/voteIcon.svg
  src/components/GameStart.jsx
  src/components/gamestart/GameStartHeader.jsx
  src/elements/Button.jsx
  src/elements/Camera2.jsx
  src/elements/Timer.jsx
  src/pages/Home.jsx
  src/pages/Room.jsx
  src/redux/modules/gameSlice.js
Labels: update

#74 Refactor/gameready : 방에 들어오는 실시간 유저의 값 확인
  src/components/Chat.jsx
  src/components/GameReady.jsx
  src/components/RoomItem.jsx
  src/components/createroom/CreateRoom.jsx
  src/elements/Camera1.jsx
  src/pages/Home.jsx
  src/pages/Room.jsx
Labels: update, TodayIDid

#76 Feature/gameprogress: 사전투표 기능 구현
  src/components/GameStart.jsx
  src/components/RoomItem.jsx
  src/components/gamestart/GameStartHeader.jsx
  src/elements/Button.jsx
  src/elements/Camera2.jsx
  src/pages/Room.jsx
  src/redux/modules/gameSlice.js
Labels: update

#92 Fix/makeroom: 방 만들기 시 하드모드 에러 처리
  src/components/createroom/CreateRoom.jsx
Labels: bug

#97 Fix/svgfile: svg 파일 오류 수정, 고양이 랜덤 보이기
  src/assets/category_animal.svg
  src/assets/category_country.svg
  src/assets/category_food.svg
  src/assets/category_place.svg
  src/assets/category_sport.svg
  src/assets/chat_profile_lion.svg
  src/assets/expressionless_cat.svg
  src/assets/game_description_2.svg
  src/assets/game_description_3.svg
  src/assets/game_description_4.svg
  src/assets/game_description_5.svg
  src/assets/game_description_one.svg
  src/assets/prepared_cat.svg
  src/assets/preparing_cat.svg
  src/assets/we_all_lie.svg
  src/assets/wink_cat.svg
  src/components/GameStart.jsx
  src/components/gameend/GameEndContents.jsx
  src/components/gamestart/GivenWord.jsx
  src/elements/Camera2.jsx
  src/elements/ModalTimer.jsx
  src/pages/Room.jsx
Labels: bug, update

#98 Refactor/gameready : 다음 페이지로 넘어가기 전 타이머 alert 구현
  src/components/GameReady.jsx
  src/components/gameready/MediumHeader.jsx
  src/components/login/kakao.jsx
Labels: update, TodayIDid

#102 Refactor/gamestart: 리팩토링, 투표 에러 수정
  src/components/GameStart.jsx
  src/components/gamestart/CorrectCardSection.jsx
  src/components/gamestart/GameStartHeader.jsx
  src/components/gamestart/GameStartTimerSection.jsx
  src/pages/Home.jsx
Labels: update

#104 Fix/login : 로그인 페이지 전체 화면 구성 수정
  public/img/kakao.png
  public/img/kakao1.png
  src/assets/kakao.svg
  src/assets/swiper_five.svg
  src/assets/swiper_four.svg
  src/assets/swiper_one.svg
  src/assets/swiper_three.svg
  src/assets/swiper_two.svg
  src/assets/we_all_lie.svg
  src/components/login/MainSwiper.jsx
  src/pages/Login.jsx
  src/pages/Room.jsx
Labels: TodayIDid

#116 Fix/login : 게임 설명 모달 색 변경
  src/GlobalStyle.jsx
  src/components/GameReady.jsx
  src/components/gameready/MainHeader.jsx
  src/components/login/MainSwiper.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/redux/modules/gameSlice.js
Labels: update, TodayIDid

#119 Fix/gameprogress : 버그 수정
  src/components/GameStart.jsx
  src/components/RoomItem.jsx
  src/components/createroom/CreateRoom.jsx
  src/components/gamestart/CorrectCardSection.jsx
  src/components/gamestart/GameStartHeader.jsx
  src/components/gamestart/GameStartTimerSection.jsx
  src/components/gamestart/SelectCategoryImg.jsx
  src/elements/Camera2.jsx
  src/elements/Timer.jsx
  src/pages/Home.jsx
  src/pages/Room.jsx
  src/redux/modules/gameSlice.js
Labels: bug, update

#122 💋 Fix/gameprogress: style : css, favicon 수정
  public/favicon.ico
  public/index.html
  public/we_all_lion.ico
  src/GlobalStyle.jsx
  src/components/GameStart.jsx
  src/components/gamestart/CorrectCardSection.jsx
  src/components/gamestart/GivenWord.jsx
  src/elements/Notice.jsx
  src/pages/Room.jsx
Labels: bug, update

#123 Fix/gamesocket : socket nickname 전달
  src/components/GameEnd.jsx
  src/components/GameReady.jsx
  src/components/RoomItem.jsx
  src/components/createroom/CreateRoom.jsx
  src/components/gameready/MainHeader.jsx
  src/components/gamestart/GameStartHeader.jsx
  src/pages/Room.jsx
Labels: bug, update

#127 Fix/gamesocket: 이름 보여주기 수정중
  src/components/GameReady.jsx
  src/components/gameready/MainHeader.jsx
Labels: bug

#128 Refactor/gameready : 유저 정보 실시간 받아오도록 수정함
  src/components/GameReady.jsx
Labels: bug

#129 Dev : 버그 수정 후 다음 테스트
  src/components/Chat.jsx
  src/components/GameReady.jsx
  src/components/UserInfo.jsx
  src/components/gameready/MainHeader.jsx
  src/components/gameready/MediumHeader.jsx
  src/components/login/Description.jsx
  src/components/login/kakao.jsx
  src/pages/Login.jsx
  src/pages/User.jsx
  src/redux/configStore.js
  src/redux/modules/userSlice.js
  src/shared/Router.js
Labels: TodayIDid

#130 Fix/gameready : ready 수정
  src/components/GameReady.jsx
  src/components/RoomItem.jsx
  src/components/createroom/CreateRoom.jsx
  src/components/gameready/MainHeader.jsx
Labels: bug

#131 Dev: ready 수정
  src/components/GameReady.jsx
  src/components/RoomItem.jsx
  src/components/createroom/CreateRoom.jsx
  src/components/gameready/MainHeader.jsx
Labels: bug

#133 Fix/gameready : 페이지 이동
  src/components/GameReady.jsx
  src/components/GameStart.jsx
  src/components/gamestart/CorrectCardSection.jsx
  src/pages/Home.jsx
  src/pages/Room.jsx
  src/redux/modules/gameSlice.js
Labels: bug

#135 🤮 fix : 타이머 오류 수정
  src/components/GameReady.jsx
Labels: bug

#138 Fix/gamestart : 게임 페이지 이동
  src/components/GameReady.jsx
  src/components/GameStart.jsx
  src/components/gamestart/GameStartHeader.jsx
Labels: bug

#140 Fix/gamestart : socket이벤트 추가
  src/components/GameStart.jsx
  src/components/RoomItem.jsx
  src/components/createroom/CreateRoom.jsx
  src/components/gamestart/GameStartHeader.jsx
  src/components/gamestart/SelectCategoryImg.jsx
  src/redux/modules/gameSlice.js
Labels: bug

#155 Fix/home : 방 개설하기 한 번만 되기
  src/components/createroom/CreateRoom.jsx
Labels: bug, update

#162 feature/user : 현재 유저 모달창 만드는중
  src/components/UserInfo.jsx
  src/components/login/kakao.jsx
  src/redux/modules/userSlice.js
Labels: TodayIDid

#168 Dev : setTimeout 오류 수정
  src/components/GameEnd.jsx
  src/components/GameStart.jsx
  src/components/gameend/GameEndContents.jsx
Labels: bug

#169 Feature/user : 유저 페이지 조회, 수정 완료
  src/components/Chat.jsx
  src/components/UserInfo.jsx
  src/redux/modules/userSlice.js
Labels: new, TodayIDid

#174 Feature/user
  src/components/GameReady.jsx
  src/components/UserInfo.jsx
  src/components/login/kakao.jsx
Labels: bug

#179 Feature/user: 수정하기 버튼 변경
  src/assets/user_make_button.svg
  src/components/UserInfo.jsx
Labels: update, TodayIDid

#183 Feature/user : 유저 페이지 공백시 알럿
  src/components/UserInfo.jsx
Labels: update, TodayIDid

#185 🤮 fix : 닉네임 중복 방지
  src/components/UserInfo.jsx
  src/redux/modules/userSlice.js
Labels: update, TodayIDid

#186 Dev : 중복방지 테스트
  src/components/UserInfo.jsx
  src/redux/modules/userSlice.js
Labels: update, TodayIDid

#191 🌻 update : 음소거 해제
  src/components/RTC.jsx
Labels: update

#196 Feature/user : og태그 추가 + 콘솔로그 방지 + 투표타임 변경
  public/index.html
  public/logo200.png
  public/we_all_lion.ico
  src/App.js
  src/components/gamestart/GameStartHeader.jsx
  src/components/login/MainSwiper.jsx
Labels: new
