Repository seunghoonKang/we-all-lie-fe, pull requests merged in 2022-11, with the labels that each got.

#7 Home 채팅방 hidden/visible 수정 사항 PR
  src/components/Chat.jsx
  src/elements/Layout.jsx
  src/pages/Home.jsx
Labels: update

#9 방만들기 모달 + 폼 구현
  .prettierrc.js
  package.json
  src/components/Chat.jsx
  src/components/RoomItem.jsx
  src/components/createroom/CreateRoom.jsx
  src/components/createroom/CreateRoomCheckBox.jsx
  src/components/createroom/CreateRoomRadio.jsx
  src/components/createroom/CreateRoomSelect.jsx
  src/components/createroom/CreateRoomTextInput.jsx
  src/pages/Home.jsx
  src/shared/Router.js
  yarn.lock
Labels: new, TodayIDid

#30 Game/game start : 게임 공통 부분 라이브쉐어로 함께 구성
  src/components/GameReady.jsx
  src/components/GameStart.jsx
  src/components/GameVote.jsx
  src/components/gameready/123.jsx
  src/components/gamestart/123.jsx
  src/components/gamevote/123.jsx
  src/elements/Camera.jsx
  src/pages/Room.jsx
Labels: new

#35 Feature/game start: 게임 진행 부분 + 버튼, 타이머 컴포넌트
  src/components/GameStart.jsx
  src/components/RoomItem.jsx
  src/components/gamestart/123.jsx
  src/components/gamestart/Timer.jsx
  src/elements/Button.jsx
  src/pages/Room.jsx
Labels: new

#43 🌻 update : CLIENT_ID, REDIRECT_URI .env 파일로 이동
  .gitignore
  src/components/GameReady.jsx
  src/components/gameready/ReadyHeader.jsx
  src/elements/Header.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Room.jsx
  src/shared/socket.js
Labels: TodayIDid

#65 Feature/gameready : 준비 버튼 누른거 확인, 게임 시작시 키워드 받아옴
  public/img/lion.png
  public/img/ready.png
  src/assets/play_modal.svg
  src/assets/r_eady.svg
  src/assets/we_all_lie_white_logo.svg
  src/components/GameReady.jsx
  src/components/gameready/HeaderSection.jsx
  src/components/gameready/ReadyButton.jsx
  src/components/gameready/ReadyHeader.jsx
  src/components/login/Description.jsx
  src/components/login/kakao.jsx
  src/elements/Camera.jsx
  src/elements/Header.jsx
  src/elements/Layout.jsx
  src/elements/Notice.jsx
  src/pages/Login.jsx
  src/pages/Room.jsx
Labels: TodayIDid
